# Generated by Django 5.2.7 on 2026-06-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="agent",
            managers=[],
        ),
    ]
